# generated by 'xml2py'
# flags 'vpx_encoder.xml -o vpx_encoder.py -l ../Release/vpxmt.dll -v'
from vpx import *
cdecl = CFUNCTYPE
stdcall = WINFUNCTYPE

VPX_DL_REALTIME = 1 # VPx REALTIME mode
VPX_DL_GOOD_QUALITY = 1000000  # VPx GOOD QUALITY
VPX_DL_BEST_QUALITY = 0 # VPx BEST QUALITY mode


VPX_FRAME_IS_KEY       = 0x1 #/**< frame is the start of a GOP */
VPX_FRAME_IS_DROPPABLE = 0x2 #/**< frame can be dropped without affecting the stream (no future frame depends on this one) */
VPX_FRAME_IS_INVISIBLE = 0x4 #/**< frame should be decoded but will not be shown */
VPX_FRAME_IS_FRAGMENT  = 0x8 #/**< this is a fragment of the encoded


# ../vpxmt/include/vpx/vpx_encoder.h 85

vpx_codec_iter_t = c_void_p
LP_vpx_codec_iter_t = POINTER(vpx_codec_iter_t)

# ../vpxmt/include/vpx/vpx_encoder.h 160
class packet(Structure):
    pass

vpx_codec_pts_t = int64_t
# ../vpxmt/include/vpx/vpx_encoder.h 106

vpx_codec_frame_flags_t = uint32_t
packet._fields_ = [
    # ../vpxmt/include/vpx/vpx_encoder.h 160
    ('buf', c_void_p),
    ('sz', size_t),
    ('pts', vpx_codec_pts_t),
    ('duration', c_ulong),
    ('flags', vpx_codec_frame_flags_t),
    ('partition_id', c_int),
]
assert sizeof(packet) == 32, sizeof(packet)
assert alignment(packet) == 8, alignment(packet)

# ../vpxmt/include/vpx/vpx_encoder.h 155
class vpx_codec_cx_pkt(Structure):
    pass
# ../vpxmt/include/vpx/vpx_encoder.h 140

vpx_codec_cx_pkt_kind = c_int # enum
VPX_CODEC_CX_FRAME_PKT = 0
VPX_CODEC_STATS_PKT = 1
VPX_CODEC_PSNR_PKT = 2
VPX_CODEC_CUSTOM_PKT = 256

# ../vpxmt/include/vpx/vpx_encoder.h 158
class N16vpx_codec_cx_pkt3DOLLAR_3E(Union):
    pass

# ../vpxmt/include/vpx/vpx_encoder.h 178
class vpx_psnr_pkt(Structure):
    pass

vpx_psnr_pkt._fields_ = [
    # ../vpxmt/include/vpx/vpx_encoder.h 178
    ('samples', c_uint * 4),
    ('sse', uint64_t * 4),
    ('psnr', c_double * 4),
]
assert sizeof(vpx_psnr_pkt) == 80, sizeof(vpx_psnr_pkt)
assert alignment(vpx_psnr_pkt) == 8, alignment(vpx_psnr_pkt)

N16vpx_codec_cx_pkt3DOLLAR_3E._fields_ = [
    # ../vpxmt/include/vpx/vpx_encoder.h 158
    ('frame', packet),
    ('twopass_stats', vpx_fixed_buf),
    ('psnr', vpx_psnr_pkt),
    ('raw', vpx_fixed_buf),
    ('pad', c_char * 124),
]
assert sizeof(N16vpx_codec_cx_pkt3DOLLAR_3E) == 128, sizeof(N16vpx_codec_cx_pkt3DOLLAR_3E)
assert alignment(N16vpx_codec_cx_pkt3DOLLAR_3E) == 8, alignment(N16vpx_codec_cx_pkt3DOLLAR_3E)

vpx_codec_cx_pkt._fields_ = [
    # ../vpxmt/include/vpx/vpx_encoder.h 155
    ('kind', vpx_codec_cx_pkt_kind),
    ('data', N16vpx_codec_cx_pkt3DOLLAR_3E),
]
assert sizeof(vpx_codec_cx_pkt) == 136, sizeof(vpx_codec_cx_pkt)
assert alignment(vpx_codec_cx_pkt) == 8, alignment(vpx_codec_cx_pkt)


# ../vpxmt/include/vpx/vpx_encoder.h 247
vpx_enc_frame_flags_t = c_long

# ../vpxmt/include/vpx/vpx_encoder.h 822
vpx_codec_encode = cdecl(vpx_codec_err_t, LP_vpx_codec_ctx_t, LP_vpx_image_t, vpx_codec_pts_t, c_ulong, vpx_enc_frame_flags_t, c_ulong) (('vpx_codec_encode', cdll.vpxmt,),)


# ../vpxmt/include/vpx/vpx_encoder.h 258
class vpx_codec_enc_cfg(Structure):
    pass
vpx_codec_enc_cfg_t = vpx_codec_enc_cfg
LP_vpx_codec_enc_cfg_t = POINTER(vpx_codec_enc_cfg_t)

# ../vpxmt/include/vpx/vpx_encoder.h 758
vpx_codec_enc_config_set = cdecl(vpx_codec_err_t, LP_vpx_codec_ctx_t, LP_vpx_codec_enc_cfg_t) (('vpx_codec_enc_config_set', cdll.vpxmt,),)
# ../vpxmt/include/vpx/vpx_encoder.h 740
vpx_codec_enc_config_default = cdecl(vpx_codec_err_t, LP_vpx_codec_iface_t, LP_vpx_codec_enc_cfg_t, c_uint) (('vpx_codec_enc_config_default', cdll.vpxmt,),)

# ../vpxmt/include/vpx/vpx_encoder.h 666
vpx_codec_enc_init_ver = cdecl(vpx_codec_err_t, LP_vpx_codec_ctx_t, LP_vpx_codec_iface_t, LP_vpx_codec_enc_cfg_t, vpx_codec_flags_t, c_int) (('vpx_codec_enc_init_ver', cdll.vpxmt,),)

VPX_ENCODER_ABI_VERSION = (3 + VPX_CODEC_ABI_VERSION)
vpx_codec_enc_init = lambda a, b, c, d: vpx_codec_enc_init_ver(a, b, c, d, VPX_ENCODER_ABI_VERSION)

# ../vpxmt/include/vpx/vpx_encoder.h 192
vpx_codec_cx_pkt_t = vpx_codec_cx_pkt
LP_vpx_codec_cx_pkt_t = POINTER(vpx_codec_cx_pkt_t)

# ../vpxmt/include/vpx/vpx_encoder.h 897
vpx_codec_get_cx_data = cdecl(LP_vpx_codec_cx_pkt_t, LP_vpx_codec_ctx_t, LP_vpx_codec_iter_t) (('vpx_codec_get_cx_data', cdll.vpxmt,),)

# ../vpxmt/include/vpx/vpx_encoder.h 912
vpx_codec_get_preview_frame = cdecl(LP_vpx_image_t, LP_vpx_codec_ctx_t) (('vpx_codec_get_preview_frame', cdll.vpxmt,),)

# ../vpxmt/include/vpx/vpx_encoder.h 870
vpx_codec_set_cx_data_buf = cdecl(vpx_codec_err_t, LP_vpx_codec_ctx_t, LP_vpx_fixed_buf_t, c_uint, c_uint) (('vpx_codec_set_cx_data_buf', cdll.vpxmt,),)

# ../vpxmt/include/vpx/vpx_encoder.h 772
vpx_codec_get_global_headers = cdecl(LP_vpx_fixed_buf_t, LP_vpx_codec_ctx_t) (('vpx_codec_get_global_headers', cdll.vpxmt,),)
