# generated by 'xml2py'
# flags 'vp8dx.xml -o vpxdx.py -l ../Release/vpxmt.dll -v'
from vpx import *
# ../vpxmt/include/vpx/vp8dx.h 34
vpx_codec_vp8_dx = cdecl(POINTER(vpx_codec_iface_t), ) (('vpx_codec_vp8_dx', cdll.vpxmt,),)
